### ISSUE TITLE
`LoggerContext` causes TS2527 when used with middleware in exported routers

### ISSUE THREAD

**Issue by SethMortenson64** [middleapi/orpc#1712]
### Environment

orpc@1.14.8, Node 24.18.0, typescript@7.0.2

### Reproduction

https://github.com/SethMortenson64/orpc-issue-reproduction

Run `npx tsc` after installing packages.

### Describe the bug

When using `LoggerContext` from `@orpc/experimental-pino` as part of an oRPC context, adding middleware and exporting a router causes TypeScript 7.0.2 to fail with the error, TS2527. `composite` in tsconfig.json must be set to `true` for this to happen. Using the middleware directly on the router does not cause the issue. This appears to be related to middleware context composition causing the private symbol from `LoggerContext` to leak into an inferred exported type.

### Additional context

`LoggerContext` contains a `unique symbol` property that isn't exported:
```
declare const CONTEXT_LOGGER_SYMBOL: unique symbol;

export interface LoggerContext {
    [CONTEXT_LOGGER_SYMBOL]?: Logger;
}
```
Because `CONTEXT_LOGGER_SYMBOL` is inaccessible from outside the package, `tsc` panics when it tries to emit declaration files for exported routers referencing this context.

Note: The code compiles on TypeScript 5.9.x without issues.

### Logs

```sh
src/index.ts:12:14 - error TS2527: The inferred type of 'router' references an inaccessible 'unique symbol' type. A type annotation is necessary.

12 export const router = base.router({ proc });
                ~~~~~~


Found 1 error in src/index.ts:12
```

**Comment by dinwwwh** [comment]
Thanks for the reproduction. Adding this import fixes it:

```ts
import { CONTEXT_LOGGER_SYMBOL } from '@orpc/experimental-pino';
```

`CONTEXT_LOGGER_SYMBOL` is already a public value export, so it isn't inaccessible.

**Comment by SethMortenson64** [comment]
> Thanks for the reproduction. Adding this import fixes it:
> 
> import { CONTEXT_LOGGER_SYMBOL } from '@orpc/experimental-pino';
> `CONTEXT_LOGGER_SYMBOL` is already a public value export, so it isn't inaccessible.

Sorry, I didn't realize that was exported. Wouldn't most people not think to add that import? Even if someone added it, their code editor would likely flag it for being an unused import. The documentation doesn't make it very clear that the import is needed.

**Comment by dinwwwh** [comment]
>  The documentation doesn't make it very clear that the import is needed.

I believe this is tsc issue not oRPC.

**Comment by SethMortenson64** [comment]
I did some more research! TypeScript 7 seems to have intentionally made the declaration emitter stricter, which is causing this issue. It now recursively validates every generic argument of an inferred type for nameability, which is why this unique symbol causes problems. This fixes that issue directly, although it doesn't seem to be ideal:
```ts
const CONTEXT_LOGGER_SYMBOL = '__orpc_context_logger__';
export interface LoggerContext {
    [CONTEXT_LOGGER_SYMBOL]: Logger | undefined;
}
```
I took some more time looking at the code, and changing this also seems to fix it:
```ts
type MergedInitialContext<TInitial extends Context, TAdditional extends Context, TCurrent extends Context> = TInitial & TAdditional;
```
For reference, this is the original code:
```ts
type MergedInitialContext<TInitial extends Context, TAdditional extends Context, TCurrent extends Context> = TInitial & Omit<TAdditional, keyof TCurrent>;
```
`Omit` seems to leak the unique symbol, which causes the error.

**Comment by dinwwwh** [comment]
Good new v2 doesn't face this issue.
